---
- name: Include variables.
  include_vars: "{{item}}"
  with_first_found:
    - "{{ ansible_facts['os_family'] }}.yml"
    - "common-default.yml"
  tags: [ipsec, config]

- import_tasks: install.deb.yml
  become: true
  when: ipsec_enabled|bool and ansible_facts["os_family"] == 'Debian'
  tags: [ipsec]

- import_tasks: install.yum.yml
  become: true
  when: ipsec_enabled|bool and ansible_facts["os_family"] == 'RedHat'
  tags: [ipsec]

- import_tasks: configure.yml
  when: ipsec_enabled|bool and (ipsec_connections|length > 0)

- import_tasks: bgp.yml
  when: ipsec_enabled|bool and ipsec_bgp|bool

- name: Ensure IPSec is started
  become: true
  service:
    name: ipsec
    state: started
    enabled: yes
  when: ipsec_enabled|bool and ansible_facts["os_family"] != 'Darwin'

- name: Ensure IPSec-route is enabled
  become: true
  service:
    name: ipsec-route
    enabled: yes
  when: ipsec_route|bool and ansible_facts["os_family"] != 'Darwin'
