---

- name: systemctl reload
  become: true
  shell: systemctl daemon-reload

- name: ipsec restart
  become: true
  service: name={{ipsec_service}} state=restarted
  when: ansible_facts["os_family"] != 'Darwin'
